# Generated by Django 6.0.6 on 2026-07-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provincias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontoturistico',
            name='Relevo',
        ),
        migrations.RemoveField(
            model_name='pontoturistico',
            name='agricultura',
        ),
        migrations.RemoveField(
            model_name='pontoturistico',
            name='caracteristicas',
        ),
        migrations.RemoveField(
            model_name='pontoturistico',
            name='clima_hidrografica',
        ),
        migrations.RemoveField(
            model_name='pontoturistico',
            name='economia',
        ),
        migrations.RemoveField(
            model_name='pontoturistico',
            name='geografica_limite',
        ),
        migrations.AddField(
            model_name='municipio',
            name='Relevo',
            field=models.TextField(blank=True, verbose_name='Relevo e Geomorfologia'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='agricultura',
            field=models.TextField(blank=True, verbose_name='Agricultura, indústria e pesca'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='caracteristicas',
            field=models.TextField(blank=True, verbose_name='Caract. Demográfica, Física-Económico e Geografica'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='clima_hidrografica',
            field=models.TextField(blank=True, verbose_name='Clima e Hidrografia'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='economia',
            field=models.TextField(blank=True, verbose_name='Sócio Demográfico e Económico'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='geografica_limite',
            field=models.TextField(blank=True, verbose_name='Situação Geográfica'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='historia',
            field=models.TextField(blank=True, verbose_name='História / Contexto'),
        ),
    ]
