# Generated by Django 6.0.6 on 2026-06-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provincias', '0002_conversaai'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='responsavel',
            field=models.TextField(blank=True),
        ),
    ]
