# Generated by Django 6.0.6 on 2026-07-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provincias', '0002_remove_pontoturistico_relevo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='Proposta',
            field=models.TextField(blank=True, verbose_name='Proposta de intervenção'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='especie_animal',
            field=models.TextField(blank=True, help_text='Só para Parques', verbose_name='Espécie Animal'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='infrastrutura',
            field=models.TextField(blank=True, verbose_name='Infra-Estruturas'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='localizacao',
            field=models.TextField(blank=True, verbose_name='Localização'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='outros_aspectos',
            field=models.TextField(blank=True, verbose_name='Outros Aspectos'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='via_acesso',
            field=models.TextField(blank=True, verbose_name='Via de Acesso'),
        ),
    ]
