# Generated by Django 6.0.6 on 2026-07-16 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provincias', '0003_pontoturistico_proposta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='Proposta',
            new_name='proposta',
        ),
    ]
