# Generated by Django 6.0.6 on 2026-06-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provincias', '0003_pontoturistico_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='melhor_epoca',
            field=models.TextField(blank=True, null=True),
        ),
    ]
