# Generated by Django 6.0.6 on 2026-06-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provincias', '0004_pontoturistico_melhor_epoca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pratotipico',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
