# Generated by Django 6.0.6 on 2026-06-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provincias', '0005_alter_pratotipico_destaque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincia',
            name='ordem',
            field=models.IntegerField(blank=True),
        ),
    ]
