# Generated by Django 6.0.6 on 2026-06-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provincias', '0006_alter_provincia_ordem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincia',
            name='ordem',
            field=models.IntegerField(unique=True),
        ),
    ]
