# Generated by Django 6.0.6 on 2026-07-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provincias', '0007_alter_provincia_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='caracteristicas',
            field=models.TextField(blank=True, verbose_name='Caract. Demográfica, Física-Económico e Geografica'),
        ),
    ]
