# Generated by Django 6.0.6 on 2026-07-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provincias', '0008_pontoturistico_caracteristicas'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='diagnostico',
            field=models.TextField(blank=True, verbose_name='Diagnóstico do Setor'),
        ),
        migrations.AddField(
            model_name='municipio',
            name='estrategia',
            field=models.TextField(blank=True, verbose_name='Estrategia para potenciar o turismo'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='Relevo',
            field=models.TextField(blank=True, verbose_name='Relevo e Geomorfologia'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='agricultura',
            field=models.TextField(blank=True, verbose_name='Agricultura, indústria e pesca'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='clima_hidrografica',
            field=models.TextField(blank=True, verbose_name='Clima e Hidrografia'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='economia',
            field=models.TextField(blank=True, verbose_name='Sócio Demográfico e Económico'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='geografica_limite',
            field=models.TextField(blank=True, verbose_name='Situação Geográfica'),
        ),
    ]
