# Generated by Django 6.0.6 on 2026-07-15 10:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provincias', '0009_municipio_diagnostico_municipio_estrategia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaturismo',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='conversaai',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='favorito',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='pontoturistico',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='pratotipico',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='regiao',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='categoriaturismo',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='conversaai',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='pratotipico',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='regiao',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
