# Generated by Django 6.0.6 on 2026-06-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiaturistico',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='guias/fotos/'),
        ),
    ]
