# Generated by Django 6.0.6 on 2026-06-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_guiaturistico_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alojamentos/restaurante/%Y/'),
        ),
        migrations.AlterField(
            model_name='tipoquarto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alojamentos/hotel/%Y/'),
        ),
    ]
