# Generated by Django 6.0.6 on 2026-06-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_restaurante_foto_alter_tipoquarto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alojamentos/hotel/%Y/'),
        ),
        migrations.AlterField(
            model_name='tipoquarto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='quartos/%Y/'),
        ),
    ]
