# Generated by Django 6.0.6 on 2026-06-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_hotel_foto_alter_tipoquarto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
