# Generated by Django 6.0.6 on 2026-06-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_hotel_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
    ]
