# Generated by Django 6.0.6 on 2026-06-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_restaurante_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
