# Generated by Django 6.0.6 on 2026-07-15 10:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_restaurante_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresaturistica',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='guiaturistico',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='itemmenu',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='restaurante',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='tipoquarto',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='empresaturistica',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='guiaturistico',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='itemmenu',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurante',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tipoquarto',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
