# Generated by Django 6.0.6 on 2026-07-15 12:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True, verbose_name='Chave')),
                ('valor', models.TextField(verbose_name='Valor')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('booleano', 'Booleano'), ('json', 'JSON')], default='texto', max_length=20)),
                ('editavel', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
                'db_table': 'core_configuracao_sistema',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('apelido', models.CharField(blank=True, max_length=100, verbose_name='Apelido')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='usuarios/fotos/%Y/%m/', verbose_name='Foto de perfil')),
                ('tipo_usuario', models.CharField(choices=[('visitante', 'Visitante'), ('empresa', 'Empresa Turística'), ('guia', 'Guia Turístico'), ('gestor_local', 'Gestor Local'), ('administrador', 'Administrador')], db_index=True, default='visitante', max_length=20, verbose_name='Tipo de usuário')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('bio', models.TextField(blank=True, verbose_name='Biografia')),
                ('idioma_preferido', models.CharField(choices=[('pt', 'Português'), ('en', 'English'), ('fr', 'Français'), ('es', 'Español')], default='pt', max_length=5, verbose_name='Idioma preferido')),
                ('notificacoes_email', models.BooleanField(default=True, verbose_name='Notificações por e-mail')),
                ('modo_escuro', models.BooleanField(default=False, verbose_name='Modo escuro')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ultimo_acesso_em', models.DateTimeField(blank=True, null=True)),
                ('ip_ultimo_acesso', models.GenericIPAddressField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'core_usuario',
            },
        ),
        migrations.CreateModel(
            name='LogAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('criacao', 'Criação'), ('edicao', 'Edição'), ('remocao', 'Remoção'), ('login', 'Login'), ('logout', 'Logout'), ('visualizou', 'Visualizou'), ('pesquisou', 'Pesquisou'), ('exportou', 'Exportou')], db_index=True, max_length=20)),
                ('descricao', models.TextField()),
                ('modelo_afetado', models.CharField(blank=True, max_length=100)),
                ('objeto_id', models.CharField(blank=True, max_length=50)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
                ('agente_usuario', models.TextField(blank=True, verbose_name='User Agent')),
                ('dados_extras', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_atividade', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Atividade',
                'verbose_name_plural': 'Logs de Atividade',
                'db_table': 'core_log_atividade',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo', models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo')], default='imagem', max_length=10)),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('ficheiro', models.FileField(upload_to='midia/%Y/%m/')),
                ('url_externa', models.URLField(blank=True, verbose_name='URL externa (YouTube, Vimeo...)')),
                ('tamanho_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('largura_px', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('altura_px', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='midias_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Mídias',
                'db_table': 'core_midia',
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo', models.CharField(choices=[('info', 'Informação'), ('sucesso', 'Sucesso'), ('aviso', 'Aviso'), ('erro', 'Erro'), ('sistema', 'Sistema')], default='info', max_length=20)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('url_destino', models.URLField(blank=True, verbose_name='Link de destino')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'db_table': 'core_notificacao',
            },
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email'], name='core_usuari_email_bbb8bb_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['tipo_usuario'], name='core_usuari_tipo_us_dbef7e_idx'),
        ),
        migrations.AddIndex(
            model_name='logatividade',
            index=models.Index(fields=['usuario', 'acao'], name='core_log_at_usuario_208ef5_idx'),
        ),
        migrations.AddIndex(
            model_name='logatividade',
            index=models.Index(fields=['modelo_afetado', 'objeto_id'], name='core_log_at_modelo__b4725e_idx'),
        ),
        migrations.AddIndex(
            model_name='logatividade',
            index=models.Index(fields=['criado_em'], name='core_log_at_criado__18d304_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['destinatario', 'lida'], name='core_notifi_destina_03393d_idx'),
        ),
    ]
