"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5o4+8tj0=blaoad9v3=vaou(v4h$jpu0=u8jdir@6^yrynx1g#'
"""
============================================================
EXPLORA REGIÃO AI — Configurações Django
============================================================
"""

import os
from pathlib import Path
from decouple import config, Csv
from datetime import timedelta

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = config('SECRET_KEY', default=SECRET_KEY)
DEBUG = config('DEBUG', default=False, cast=bool)

# ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')
ALLOWED_HOSTS=["*"]

# ============================================================
# APLICAÇÕES https://localhost:8000/
# ============================================================
DJANGO_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
   
    'django.contrib.sites',
    'django.contrib.humanize',
    "cloudinary",
    "cloudinary_storage",
]

THIRD_PARTY_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'modeltranslation',
    'auditlog',
    'storages',
    'django_celery_beat',
    'django_celery_results',
    'drf_spectacular',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'leaflet'
]

LOCAL_APPS = [
    'apps.authenticate',
    'apps.provincias',
    'apps.empresas',
    'apps.ponto_turismo',
    # 'apps.empresas',
    # 'apps.eventos',
    # 'apps.roteiros',
    # 'apps.avaliacoes',
    # 'apps.comunidade',
    # 'apps.guia_ai',
    # 'apps.painel',
]



INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

SITE_ID = 1

# ============================================================
# MIDDLEWARE
# ============================================================
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

CLOUDINARY_STORAGE = {
    "CLOUD_NAME": os.getenv("CLOUD_NAME"),
    "API_KEY": os.getenv("CLOUD_API_KEY"),
    "API_SECRET": os.getenv("CLOUD_API_SECRET"),
}


DEFAULT_FILE_STORAGE = (
    "cloudinary_storage.storage.MediaCloudinaryStorage"
)

ROOT_URLCONF = 'config.urls'
WSGI_APPLICATION = 'config.wsgi.application'

# ============================================================
# BANCO DE DADOS — PostgreSQL + PostGIS
# ============================================================
DATABASES = {
    "default": dj_database_url.config(
        default=os.environ.get("DATABASE_URL")
    )
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': config('NAME_DB'),
#         'USER': config('USER_DB'),
#         'PASSWORD': config('PASSWORD_DB'),
#         'HOST': config('HOST_DB'),
#         'PORT': config('PORT_DB'),
#     }
# }

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.debug',
            ],
        },
    },
]

# ============================================================
# CACHE
# ============================================================
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
    }
}

# ============================================================
# CELERY — Processamento Assíncrono
# ============================================================
CELERY_BROKER_URL         = config('REDIS_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND     = 'django-db'
CELERY_ACCEPT_CONTENT     = ['json']
CELERY_TASK_SERIALIZER    = 'json'
CELERY_RESULT_SERIALIZER  = 'json'
CELERY_TIMEZONE           = 'Africa/Luanda'
CELERY_BEAT_SCHEDULER     = 'django_celery_beat.schedulers:DatabaseScheduler'

# ============================================================
# INTERNACIONALIZAÇÃO
# ============================================================
LANGUAGE_CODE = 'pt'
TIME_ZONE     = 'Africa/Luanda'
USE_I18N = True
USE_L10N = True
USE_TZ   = True

LANGUAGES = [
    ('pt', 'Português'),
    ('en', 'English'),
    ('fr', 'Français'),
    ('es', 'Español'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

# ============================================================
# AUTENTICAÇÃO
# ============================================================
AUTH_USER_MODEL = 'authenticate.Usuario'

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
     'OPTIONS': {'min_length': 8}},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
]

# ============================================================
# JWT
# ============================================================
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME':  timedelta(hours=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS':  True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ============================================================
# REST FRAMEWORK
# ============================================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
    },
}

# ============================================================
# FICHEIROS ESTÁTICOS E MEDIA
# ============================================================
STATIC_URL  = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL  = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================
# SEGURANÇA (Produção)
# ============================================================
if not DEBUG:
    SECURE_HSTS_SECONDS            = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_SSL_REDIRECT            = True
    SESSION_COOKIE_SECURE          = True
    CSRF_COOKIE_SECURE             = True
    SECURE_BROWSER_XSS_FILTER      = True
    SECURE_CONTENT_TYPE_NOSNIFF    = True
    X_FRAME_OPTIONS                = 'DENY'
    
JAZZMIN_SETTINGS = {

    # ===========================
    # GERAL
    # ===========================
    "site_title": "Sistema Académico",
    "site_header": "Painel Administrativo",
    "site_brand": "SIGA",
    "welcome_sign": "Bem-vindo ao Sistema Integrado de Gestão Académica",

    "copyright": "© 2026 SIGA - Todos os direitos reservados",

    "site_logo": "img/logo.png",
    "login_logo": "img/logo.png",
    "login_logo_dark": "img/logo.png",
    "site_logo_classes": "img-circle elevation-3",
    "site_icon": "img/favicon.ico",

    "search_model": [
        "authenticate.usuario",
        "auth.Group",
    ],

    "user_avatar": None,

    # ===========================
    # MENU SUPERIOR
    # ===========================

    "topmenu_links": [

        {
            "model": "authenticate.usuario",
        },

        {
            "model": "auth.Group",
        },

    ],

    # ===========================
    # MENU DO UTILIZADOR
    # ===========================

    "usermenu_links": [

        {
            "name": "Página Inicial",
            "url": "/",
        },

      

    ],

    # ===========================
    # MENU LATERAL
    # ===========================

    "show_sidebar": True,
    "navigation_expanded": True,

    "hide_apps": [

    ],

    "hide_models": [

    ],

    "order_with_respect_to": [

        "auth",

    ],

    "custom_links": {

    },

    # ===========================
    # ÍCONES
    # ===========================

    "icons": {

        "authenticate": "fas fa-user-shield",
        "authenticate.usuario": "fas fa-user",
        "auth.group": "fas fa-users",

    },

    "default_icon_parents": "fas fa-folder-open",
    "default_icon_children": "fas fa-circle",

    # ===========================
    # MODAIS
    # ===========================

    "related_modal_active": True,

    # ===========================
    # PERSONALIZAÇÃO
    # ===========================

    "custom_css": "css/admin.css",
    #"custom_js": "js/admin.js",

    "use_google_fonts_cdn": True,

    "show_ui_builder": False,

    # ===========================
    # FORMULÁRIOS
    # ===========================

    "changeform_format": "horizontal_tabs",

    "changeform_format_overrides": {

        "authenticate.usuario": "collapsible",
        "auth.group": "vertical_tabs",

    },

    "language_chooser": True,
}

JAZZMIN_UI_TWEAKS = {

    "navbar": "navbar-dark navbar-navy",

    "no_navbar_border": True,

    "navbar_fixed": True,

    "layout_boxed": False,

    "footer_fixed": False,

    "sidebar_fixed": True,

    "sidebar": "sidebar-dark-navy",

    "sidebar_nav_small_text": False,

    "sidebar_disable_expand": False,

    "sidebar_nav_child_indent": True,

    "sidebar_nav_compact_style": False,

    "sidebar_nav_legacy_style": False,

    "sidebar_nav_flat_style": False,

    "theme": "flatly",

    "dark_mode_theme": "darkly",

    "button_classes": {

        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"

    }

}